server:
  port: 8083

spring:
  application:
    name: transaction-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5434/transaction_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # depois: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      indent_output: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE