server:
  port: 8084

spring:
  application:
    name: analytics-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/analytics_db

  jackson:
    serialization:
      indent_output: true

management:
  endpoints:
    web:
      exposure:
        include: health,info