server:
  port: 8084

spring:
  application:
    name: analytics-service

  jackson:
    serialization:
      indent_output: true
  mongodb:
    uri: mongodb://mongo:mongo@localhost:27017/analytics_db?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: health,info