server:
  port: 8084

spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # depois: validate
    show-sql: false      # analytics costuma ser mais silencioso
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      indent_output: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: INFO