apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: financial-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: account-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: INTERNAL_API_KEY
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-account:5432/account_db
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 768Mi
              cpu: 750m
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: financial-dashboard
spec:
  selector:
    app: account-service
  ports:
    - port: 8082
      targetPort: 8082
